# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
x = iris.data
y = iris.target

In [ ]:
x.shape, y.shape

((150, 4), (150,))

In [ ]:
############
#train set / test set 분리
#조건1. test set size = 10%
#조건2. 난수 고정 = 2023
############

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 2023)

In [ ]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((135, 4), (135,), (15, 4), (15,))

In [ ]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
class_n = len(np.unique(y_train)) #y_train을 이용해서 클래스가 3개인 것을 확인했으니

In [ ]:
#######################
# 어떤 전처리 작업 필요 : One - Hot encoding
# Hint : y.shape
#y가 setosa, wesicolor, virginica 이렇게 가진다 각각으로 나눠서 이진분류한다 1개 노드-> 3개 노드
#softmax를 이용해서 3개 노드의 합을 1로 만들어준다
#######################
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, class_n) #y_train을 이용해야 한다
y_test = to_categorical(y_test, class_n) #y_test을 이용해야 한다

In [ ]:
y_train.shape

(135, 3)

In [ ]:
########
# 모델링
########
#1. 세션 클리어
keras.backend.clear_session()

#2. 모델 선언
model = keras.models.Sequential()

#3. 레이어 조립
model.add(keras.layers.Input(shape = (4,)))
model.add(keras.layers.Dense(3, activation = "softmax"))

#4. 컴파일
# model.compile(loss = "categorical_crossentropy", metrics = ["accuracy"], optimizer = "adam")
model.compile(loss = keras.losses.categorical_crossentropy, metrics = ["accuracy"], optimizer = "adam")
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 0s 5ms/step - loss: 2.8652 - accuracy: 0.3407
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 2.7638 - accuracy: 0.3407
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 2.6668 - accuracy: 0.3407
Epoch 4/10
5/5 [==============================] - 0s 8ms/step - loss: 2.5684 - accuracy: 0.3407
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 2.4731 - accuracy: 0.3407
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 2.3800 - accuracy: 0.3407
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 2.2901 - accuracy: 0.3407
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 2.2013 - accuracy: 0.3407
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 2.1171 - accuracy: 0.3407
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 2.0383 - accuracy: 0.3407


In [ ]:
###########
# 모델 예측
###########
y_pred = model.predict(x)

5/5 [==============================] - 0s 3ms/step


In [ ]:
print(y_pred[:10])
print(y[:10])

[[0.86213356 0.12177509 0.01609134]
 [0.86631495 0.11101788 0.02266711]
 [0.841152   0.1367044  0.02214361]
 [0.8433699  0.12832728 0.02830284]
 [0.8508848  0.13265514 0.01646003]
 [0.8825923  0.10210843 0.01529919]
 [0.83166206 0.14377956 0.02455832]
 [0.8621045  0.11868297 0.01921253]
 [0.8316894  0.13561466 0.03269596]
 [0.8627988  0.11516572 0.02203547]]
[0 0 0 0 0 0 0 0 0 0]


# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((135, 4), (15, 4), (135, 3), (15, 3))

In [ ]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (4,)))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(3, activation = "softmax"))

model.compile(loss = "categorical_crossentropy", metrics = ["accuracy"], optimizer = "adam")

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 1s 5ms/step - loss: 1.3143 - accuracy: 0.0667
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 1.1350 - accuracy: 0.3407
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 1.0411 - accuracy: 0.3481
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9739 - accuracy: 0.4000
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9108 - accuracy: 0.4593
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.8686 - accuracy: 0.4593
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.8322 - accuracy: 0.6519
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 0.7995 - accuracy: 0.7407
Epoch 9/10
5/5 [==============================] - 0s 5ms/step - loss: 0.7679 - accuracy: 0.7407
Epoch 10/10
5/5 [==============================] - 0s 6ms/step - loss: 0.7375 - accuracy: 0.7630


In [ ]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)

1/1 [==============================] - 0s 69ms/step


In [ ]:
print(y_pred[:10])
print(y_test[:10])

[[0.12943412 0.25956562 0.6110003 ]
 [0.24341416 0.38513598 0.3714498 ]
 [0.24109569 0.36770317 0.3912011 ]
 [0.12744732 0.24891005 0.62364256]
 [0.20764437 0.3673273  0.42502826]
 [0.14137606 0.27059254 0.58803135]
 [0.2152133  0.3217252  0.46306142]
 [0.24345085 0.36111426 0.3954348 ]
 [0.57505643 0.30746272 0.11748081]
 [0.24007425 0.370743   0.38918278]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
