# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
li = input_layer = keras.layers.Input(shape=(1,))
ol = output_layer = keras.layers.Dense(1, activation = "linear")(li)

# 모델의 시작과 끝을 지정
model = keras.models.Model(li, ol)

# 컴파일 해주렴
model.compile(loss='mse', optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 873ms/step - loss: 74.9620
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 74.7558
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 74.5499
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 74.3443
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 74.1390
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 73.9341
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 73.7294
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 73.5251
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 73.3210
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 73.1174


In [5]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 110ms/step
[9.99511778e-03 1.16537881e+00 2.32076263e+00 3.47614646e+00
 4.63152981e+00 5.78691339e+00 6.94229746e+00 8.09768105e+00
 9.25306511e+00 1.04084492e+01 1.15638323e+01 1.27192163e+01
 1.38746004e+01 1.50299835e+01 1.61853657e+01 1.73407497e+01
 1.84961338e+01 1.96515179e+01 2.08069019e+01 2.19622841e+01]


## Now, Your turn!

In [10]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [11]:
#1. 세션 클리어
keras.backend.clear_session()

#2. 레이어들을 연결
il = keras.layers.Input(shape = (1, ))
ol = keras.layers.Dense(1)(il)

#3. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

#4. 컴파일
model.compile(loss = "mse", optimizer = "adam")

#5. 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
1/1 [==============================] - 1s 564ms/step - loss: 188.0233
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 187.7250
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 187.4270
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 187.1293
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 186.8320
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 186.5349
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 186.2382
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 185.9417
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 185.6456
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 185.3499


In [13]:
y_pred = model.predict(x)
y_pred[:5]

1/1 [==============================] - 0s 69ms/step


array([[-0.00999574],
       [-1.1086342 ],
       [-2.2072728 ],
       [-3.3059113 ],
       [-4.40455   ]], dtype=float32)

In [14]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [6]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [7]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [8]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 모델의 시작과 끝을 지정
model = keras.models.Model(il, ol)

# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [9]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 1s 797ms/step - loss: 0.6712 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 16ms/step - loss: 0.6695 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 0.6679 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6662 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6646 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 0.6629 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 17ms/step - loss: 0.6613 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 0.6597 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6581 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6565 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1

## Now, Your turn!

In [15]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [18]:
x.shape, y.shape

((40,), (40,))

In [16]:
#라이브러리
import tensorflow as tf
from tensorflow import keras
import numpy as np

#1. 세션 초기화
keras.backend.clear_session()

#2. 레이어 연결
il = keras.layers.Input(shape = (1, ))
ol = keras.layers.Dense(1, activation = "sigmoid")(il)

#3. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

#4. 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')
#5. 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [17]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
2/2 [==============================] - 1s 15ms/step - loss: 0.6432 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 11ms/step - loss: 0.6369 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 10ms/step - loss: 0.6315 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 10ms/step - loss: 0.6257 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 10ms/step - loss: 0.6213 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 12ms/step - loss: 0.6157 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 8ms/step - loss: 0.6121 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 7ms/step - loss: 0.6090 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 10ms/step - loss: 0.6048 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6026 - accuracy: 0.5250
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [19]:
y_pred = model.predict(x)
y_pred[:5]

2/2 [==============================] - 0s 6ms/step


array([[0.49580315],
       [0.5027532 ],
       [0.50970215],
       [0.5166474 ],
       [0.5235862 ]], dtype=float32)

In [20]:
y[:5]

array([0, 0, 0, 0, 0])