# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
li = input_layer = keras.layers.Input(shape=(1,))
ol = output_layer = keras.layers.Dense(1, activation = "linear")(li)

# 모델의 시작과 끝을 지정
model = keras.models.Model(li, ol)

# 컴파일 해주렴
model.compile(loss='mse', optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 5s 5s/step - loss: 1560.9447
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 1559.9998
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 1559.0551
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 1558.1107
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 1557.1670
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 1556.2233
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 1555.2799
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 1554.3367
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 1553.3938
Epoch 10/10
1/1 [==============================] - 0s 13ms/step - loss: 1552.4515


In [5]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 98ms/step
[ 9.99898091e-03 -1.61178768e+00 -3.23357439e+00 -4.85536146e+00
 -6.47714806e+00 -8.09893417e+00 -9.72072124e+00 -1.13425074e+01
 -1.29642944e+01 -1.45860815e+01 -1.62078686e+01 -1.78296547e+01
 -1.94514427e+01 -2.10732288e+01 -2.26950150e+01 -2.43168030e+01
 -2.59385891e+01 -2.75603752e+01 -2.91821632e+01 -3.08039494e+01]


## Now, Your turn!

In [6]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [7]:
#1. 세션 클리어
keras.backend.clear_session()

#2. 레이어들을 연결
il = keras.layers.Input(shape = (1, ))
ol = keras.layers.Dense(1)(il)

#3. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

#4. 컴파일
model.compile(loss = "mse", optimizer = "adam")

#5. 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
1/1 [==============================] - 1s 592ms/step - loss: 602.2267
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 601.6581
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 601.0898
Epoch 4/10
1/1 [==============================] - 0s 14ms/step - loss: 600.5219
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 599.9542
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 599.3868
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 598.8197
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 598.2529
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 597.6866
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 597.1204


In [23]:
y_pred = model.predict(x)
print(y_pred[:5])
print(y[:5])

2/2 [==============================] - 0s 6ms/step
[[0.5045009 ]
 [0.19758779]
 [0.05620608]
 [0.01419839]
 [0.00347123]]
[0 0 0 0 0]


## Quick Logistic Regression!

In [11]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [12]:
x = np.array(range(20)) 
y = np.array([0] * 10 + [1] * 10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [24]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 모델의 시작과 끝을 지정
model = keras.models.Model(il, ol)

# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [14]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 1s 613ms/step - loss: 0.6992 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 15ms/step - loss: 0.6973 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6955 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6937 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6919 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6902 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6884 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6866 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6848 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6831 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 

## Now, Your turn!

In [15]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [16]:
x.shape, y.shape

((40,), (40,))

In [17]:
#라이브러리
import tensorflow as tf
from tensorflow import keras
import numpy as np

#1. 세션 초기화
keras.backend.clear_session()

#2. 레이어 연결
il = keras.layers.Input(shape = (1, ))
ol = keras.layers.Dense(1, activation = "sigmoid")(il)

#3. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

#4. 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')
#5. 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [18]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
2/2 [==============================] - 1s 12ms/step - loss: 21.2353 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 8ms/step - loss: 21.2064 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 10ms/step - loss: 21.1808 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 7ms/step - loss: 21.1545 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 8ms/step - loss: 21.1250 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 7ms/step - loss: 21.0967 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 7ms/step - loss: 21.0673 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 21.0386 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 21.0068 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 7ms/step - loss: 20.9810 - accuracy: 0.4750
[0 0 0 0 0 0 0 0 0 0 0 0 0 

In [25]:
y_pred = model.predict(x)
print(y_pred[:5])
print(y[:5])

2/2 [==============================] - 0s 4ms/step
[[0.5       ]
 [0.76094663]
 [0.91017336]
 [0.969928  ]
 [0.9903538 ]]
[0 0 0 0 0]
