# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [11]:
import pandas as pd

In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
california = fetch_california_housing()

In [3]:
type(california) #Bunch : python dict와 유사함, key(data) : value(target)

sklearn.utils._bunch.Bunch

In [4]:
x = california.data
y = california.target

In [5]:
x.shape, y.shape

((20640, 8), (20640,))

In [16]:
type(x)

numpy.ndarray

In [9]:
pd.DataFrame(x, columns = california.feature_names).head(2)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127    1.02381       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137    0.97188      2401.0  2.109842     37.86   

   Longitude  
0    -122.23  
1    -122.22

In [10]:
pd.DataFrame(y, columns = california.target_names).head(2)

MedHouseVal
0        4.526
1        3.585

In [12]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [13]:
########
# 모델링
########

#1. 세션 클리어
keras.backend.clear_session()

#2. 모델 블록 발판 생성
model = keras.models.Sequential()

#3. 모델 블록 조립
model.add(keras.layers.Input(shape = (8,)))
model.add(keras.layers.Dense(1))

#컴파일
model.compile(loss = "mse", optimizer = "adam")

#양념
model.summary() #편향값이 추가 돼서 파라미터 값은 9개
#y = w1x1 + w2x2 + ... w8x8 + w0(편향값)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [17]:
###########
# 모델 학습
###########
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
645/645 [==============================] - 5s 2ms/step - loss: 5273.5708
Epoch 2/10
645/645 [==============================] - 1s 2ms/step - loss: 273.1009
Epoch 3/10
645/645 [==============================] - 1s 2ms/step - loss: 51.6766
Epoch 4/10
645/645 [==============================] - 1s 2ms/step - loss: 42.9916
Epoch 5/10
645/645 [==============================] - 1s 2ms/step - loss: 38.0350
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 32.6696
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 28.6248
Epoch 8/10
645/645 [==============================] - 2s 2ms/step - loss: 24.9998
Epoch 9/10
645/645 [==============================] - 1s 2ms/step - loss: 22.5221
Epoch 10/10
645/645 [==============================] - 1s 2ms/step - loss: 19.5004


In [18]:
###########
# 모델 예측
###########
y_pred = model.predict(x)
print(y_pred[:5].reshape(-1))
print(y[:5])

645/645 [==============================] - 1s 2ms/step
[3.9743085 3.2148619 3.7907758 2.985826  2.1338022]
[4.526 3.585 3.521 3.413 3.422]


# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [19]:
x.shape, y.shape

((20640, 8), (20640,))

In [20]:
########
# 모델링 : Sequetial API
########

#1. 세션 클리어
keras.backend.clear_session()

#2. 모델 선언
model = keras.models.Sequential()

#3. 모델 블록 조립
model.add(keras.layers.Input(shape = (8, )))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(1))

#4. 컴파일
model.compile(loss = "mse", optimizer = "adam")

#양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,377
Trainable params: 1,377
Non-trainable params: 0
_________________________________________________________________


In [21]:
###########
# 모델 학습
###########

model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
645/645 [==============================] - 3s 3ms/step - loss: 588.8121
Epoch 2/10
645/645 [==============================] - 1s 2ms/step - loss: 2.5022
Epoch 3/10
645/645 [==============================] - 1s 2ms/step - loss: 2.2235
Epoch 4/10
645/645 [==============================] - 1s 2ms/step - loss: 2.6886
Epoch 5/10
645/645 [==============================] - 1s 2ms/step - loss: 3.7681
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 5.6934
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 3.0748
Epoch 8/10
645/645 [==============================] - 2s 2ms/step - loss: 1.6609
Epoch 9/10
645/645 [==============================] - 2s 3ms/step - loss: 21.3223
Epoch 10/10
645/645 [==============================] - 1s 2ms/step - loss: 5.0214


In [22]:
###########
# 모델 예측
###########

y_pred = model.predict(x)
print(y_pred[:5])
print(y[:5])

645/645 [==============================] - 1s 1ms/step
[[3.5925422]
 [2.2738552]
 [3.267993 ]
 [2.6271076]
 [1.9076122]]
[4.526 3.585 3.521 3.413 3.422]
