# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
california = fetch_california_housing()

In [ ]:
type(california) #Bunch : python dict와 유사함, key(data) : value(target)

sklearn.utils.Bunch

In [ ]:
x = california.data
y = california.target

In [ ]:
x.shape, y.shape

((20640, 8), (20640,))

In [ ]:
pd.DataFrame(x, columns = california.feature_names).head(2)

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22

[2 rows x 8 columns]

In [ ]:
pd.DataFrame(y, columns = california.target_names).head(2)

MedHouseVal
0        4.526
1        3.585

In [ ]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [ ]:
########
# 모델링
########

#1. 세션 클리어
keras.backend.clear_session()

#2. 모델 블록 발판 생성
model = keras.models.Sequential()

#3. 모델 블록 조립
model.add(keras.layers.Input(shape = (8,)))
model.add(keras.layers.Dense(1))

#컴파일
model.compile(loss = "mse", optimizer = "adam")

#양념
model.summary() #편향값이 추가 돼서 파라미터 값은 9개
#y = w1x1 + w2x2 + ... w8x8 + w0(편향값)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
645/645 [==============================] - 1s 1ms/step - loss: 608174.9375
Epoch 2/10
645/645 [==============================] - 1s 1ms/step - loss: 44726.5938
Epoch 3/10
645/645 [==============================] - 1s 1ms/step - loss: 2416.4561
Epoch 4/10
645/645 [==============================] - 1s 1ms/step - loss: 1218.1888
Epoch 5/10
645/645 [==============================] - 1s 1ms/step - loss: 716.2839
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 360.1765
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 163.2289
Epoch 8/10
645/645 [==============================] - 1s 1ms/step - loss: 84.7283
Epoch 9/10
645/645 [==============================] - 1s 1ms/step - loss: 60.9771
Epoch 10/10
645/645 [==============================] - 1s 1ms/step - loss: 51.9220


In [ ]:
###########
# 모델 예측
###########
y_pred = model.predict(x)

645/645 [==============================] - 1s 1ms/step


In [ ]:
y_pred[:5].reshape(-1)

array([4.60843  , 4.108385 , 4.694105 , 3.6611576, 3.0642185],
      dtype=float32)

In [ ]:
y[:5]

array([4.526, 3.585, 3.521, 3.413, 3.422])

# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [ ]:
x.shape, y.shape

((20640, 8), (20640,))

In [ ]:
########
# 모델링 : Sequetial API
########

#1. 세션 클리어
keras.backend.clear_session()

#2. 모델 선언
model = keras.models.Sequential()

#3. 모델 블록 조립
model.add(keras.layers.Input(shape = (8, )))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(1))

#4. 컴파일
model.compile(loss = "mse", optimizer = "adam")

#양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,377
Trainable params: 1,377
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########

model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
645/645 [==============================] - 2s 2ms/step - loss: 120.1371
Epoch 2/10
645/645 [==============================] - 1s 2ms/step - loss: 1.6901
Epoch 3/10
645/645 [==============================] - 1s 2ms/step - loss: 1.2539
Epoch 4/10
645/645 [==============================] - 1s 2ms/step - loss: 1.5706
Epoch 5/10
645/645 [==============================] - 1s 2ms/step - loss: 2.2034
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 19.2872
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 1.5269
Epoch 8/10
645/645 [==============================] - 1s 2ms/step - loss: 1.2186
Epoch 9/10
645/645 [==============================] - 1s 2ms/step - loss: 1.6372
Epoch 10/10
645/645 [==============================] - 1s 2ms/step - loss: 1.5458


In [ ]:
###########
# 모델 예측
###########

y_pred = model.predict(x)

645/645 [==============================] - 1s 1ms/step


In [ ]:
print(y_pred[:5])
print(y[:5])

[[3.370416 ]
 [3.5432274]
 [3.668609 ]
 [2.8063767]
 [1.863681 ]]
[4.526 3.585 3.521 3.413 3.422]
