# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
############
#train set / test set 분리
#조건1. test set size = 10%
#조건2. 난수 고정 = 2023
############

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 2023)

In [6]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((135, 4), (135,), (15, 4), (15,))

In [7]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [8]:
class_n = len(np.unique(y_train)) #y_train을 이용해서 클래스가 3개인 것을 확인했으니

In [9]:
#######################
# 어떤 전처리 작업 필요 : One - Hot encoding
# Hint : y.shape
#y가 setosa, wesicolor, virginica 이렇게 가진다 각각으로 나눠서 이진분류한다 1개 노드-> 3개 노드
#softmax를 이용해서 3개 노드의 합을 1로 만들어준다
#######################
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, class_n) #y_train을 이용해야 한다
y_test = to_categorical(y_test, class_n) #y_test을 이용해야 한다

In [10]:
y_train.shape

(135, 3)

In [11]:
########
# 모델링
########
#1. 세션 클리어
keras.backend.clear_session()

#2. 모델 선언
model = keras.models.Sequential()

#3. 레이어 조립
model.add(keras.layers.Input(shape = (4,)))
model.add(keras.layers.Dense(3, activation = "softmax"))

#4. 컴파일
# model.compile(loss = "categorical_crossentropy", metrics = ["accuracy"], optimizer = "adam")
model.compile(loss = keras.losses.categorical_crossentropy, metrics = ["accuracy"], optimizer = "adam")
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [12]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 4s 6ms/step - loss: 4.2077 - accuracy: 0.3407
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 4.1029 - accuracy: 0.3407
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 3.9960 - accuracy: 0.3407
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 3.8889 - accuracy: 0.3407
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 3.7824 - accuracy: 0.3407
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 3.6774 - accuracy: 0.3407
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 3.5703 - accuracy: 0.3407
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 3.4636 - accuracy: 0.3407
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 3.3559 - accuracy: 0.3407
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 3.2546 - accuracy: 0.3407


In [13]:
###########
# 모델 예측
###########
y_pred = model.predict(x)
print(y_pred[:10])
print(y[:10])

5/5 [==============================] - 0s 2ms/step
[[0.9450314  0.00225253 0.05271601]
 [0.9421373  0.00346413 0.05439848]
 [0.93112534 0.00368543 0.06518926]
 [0.932014   0.00488092 0.06310509]
 [0.9408972  0.00240176 0.05670095]
 [0.9549744  0.00186458 0.043161  ]
 [0.9265875  0.00424297 0.06916943]
 [0.94427973 0.00279509 0.05292528]
 [0.92307585 0.00616419 0.07075998]
 [0.9437182  0.00335011 0.05293171]]
[0 0 0 0 0 0 0 0 0 0]


# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [14]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((135, 4), (15, 4), (135, 3), (15, 3))

In [15]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (4,)))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(3, activation = "softmax"))

model.compile(loss = "categorical_crossentropy", metrics = ["accuracy"], optimizer = "adam")

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [16]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 1s 6ms/step - loss: 1.1478 - accuracy: 0.3407
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 1.0255 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.9911 - accuracy: 0.6963
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.9512 - accuracy: 0.6593
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 0.8869 - accuracy: 0.6741
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.8355 - accuracy: 0.6741
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.8018 - accuracy: 0.6815
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 0.7715 - accuracy: 0.6815
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 0.7434 - accuracy: 0.6815
Epoch 10/10
5/5 [==============================] - 0s 6ms/step - loss: 0.7146 - accuracy: 0.7185


In [17]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
print(y_pred[:10])
print(y_test[:10])

1/1 [==============================] - 0s 48ms/step
[[0.10908389 0.3636257  0.5272904 ]
 [0.2142109  0.39249283 0.39329627]
 [0.21932039 0.39120933 0.38947034]
 [0.10476111 0.4232256  0.4720133 ]
 [0.17141283 0.4006717  0.42791548]
 [0.12253841 0.35256025 0.5249013 ]
 [0.19758773 0.39985856 0.40255374]
 [0.221636   0.39757472 0.38078925]
 [0.63713783 0.22355206 0.13931006]
 [0.19916782 0.4047184  0.39611384]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
