# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
cancer = load_breast_cancer() #분류 문제임

In [ ]:
x = cancer.data
y = cancer.target

In [ ]:
x.shape, y.shape

((569, 30), (569,))

In [ ]:
############
#train set / test set 분리
#조건 1. test set : 20%
#조건 2. 난수 고정 : 2023
############

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 2023)

In [ ]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [ ]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

In [ ]:
########
# 모델링
########

#1번. 세션 클리어
keras.backend.clear_session()

#2번. 모델 선언
model = keras.models.Sequential()

#3번. 레이어 조립
model.add(keras.layers.Input(shape = (30, )))
model.add(keras.layers.Dense(1, activation = "sigmoid"))

#4번. 컴파일
model.compile(loss = keras.losses.binary_crossentropy, metrics = ["accuracy"], optimizer = "adam")

#양념
model.summary()
#sequential 특징은 Input layer가 summary에 출력 안된다

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose = 1)
#우리의 목적은 loss를 줄이는 것, accuracy는 보조 지표, 항상 서로 반비례 하지 않는다

Epoch 1/10
15/15 [==============================] - 1s 4ms/step - loss: 160.4505 - accuracy: 0.6286
Epoch 2/10
15/15 [==============================] - 0s 5ms/step - loss: 145.1551 - accuracy: 0.6286
Epoch 3/10
15/15 [==============================] - 0s 5ms/step - loss: 130.0400 - accuracy: 0.6286
Epoch 4/10
15/15 [==============================] - 0s 3ms/step - loss: 114.5185 - accuracy: 0.6286
Epoch 5/10
15/15 [==============================] - 0s 3ms/step - loss: 98.5985 - accuracy: 0.6286
Epoch 6/10
15/15 [==============================] - 0s 3ms/step - loss: 83.1119 - accuracy: 0.6286
Epoch 7/10
15/15 [==============================] - 0s 3ms/step - loss: 67.6409 - accuracy: 0.6286
Epoch 8/10
15/15 [==============================] - 0s 3ms/step - loss: 51.4779 - accuracy: 0.6286
Epoch 9/10
15/15 [==============================] - 0s 3ms/step - loss: 35.8515 - accuracy: 0.6264
Epoch 10/10
15/15 [==============================] - 0s 3ms/step - loss: 22.9079 - accuracy: 0.4000


In [ ]:
###########
# 모델 예측
###########

y_pred = model.predict(x_test)

4/4 [==============================] - 0s 3ms/step


In [ ]:
y_pred[:10].reshape(-1)

array([1.0000000e+00, 9.8675674e-01, 9.6351570e-01, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.3912910e-01, 9.9999678e-01,
       8.6961109e-06, 2.9847110e-02], dtype=float32)

In [ ]:
y_test[:10] #모델이 다 틀렸다..

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 1])

# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [ ]:
x_train.shape, y_train.shape

((455, 30), (455,))

In [ ]:
########
# 모델링 : Sequential API
########
#세션 클리어
keras.backend.clear_session()

#모델 선언
model = keras.models.Sequential()

#레이어 조립
model.add(keras.layers.Input(shape = (30, )))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(32, activation = "relu"))
model.add(keras.layers.Dense(1, activation = "sigmoid")) #분류 문제이기 때문!!!!

#컴파일
model.compile(loss = "binary_crossentropy", metrics = ["accuracy"], optimizer = "adam") #metrics : 보조 지표

#요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs = 10, verbose = 1)

Epoch 1/10
15/15 [==============================] - 1s 3ms/step - loss: 155.2846 - accuracy: 0.6286
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 33.3602 - accuracy: 0.5758
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 12.9776 - accuracy: 0.3780
Epoch 4/10
15/15 [==============================] - 0s 3ms/step - loss: 3.1855 - accuracy: 0.7187
Epoch 5/10
15/15 [==============================] - 0s 3ms/step - loss: 1.9079 - accuracy: 0.7077
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 1.3525 - accuracy: 0.8000
Epoch 7/10
15/15 [==============================] - 0s 3ms/step - loss: 0.9960 - accuracy: 0.8330
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.7129 - accuracy: 0.8374
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5725 - accuracy: 0.8505
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.4267 - accuracy: 0.8637


In [ ]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)

4/4 [==============================] - 0s 3ms/step


In [ ]:
y_pred[:10].reshape(-1)

array([1.1304182e-03, 8.8271362e-01, 8.8315326e-01, 4.7999301e-08,
       1.6209992e-13, 7.4897557e-08, 9.3678123e-01, 3.5506868e-01,
       8.6985540e-01, 9.7426695e-01], dtype=float32)

In [ ]:
y_test[:10]

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 1])