# Keras로 Linear&Logistic Regression 조금 더 맛보기
---

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

##Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [4]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [5]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [ ]:
#1번 세션 클리어 : 이미 만들어진 모델이 있다면 그 모델을 없앤다
keras.backend.clear_session()

#2번 모델 선언(모델 발판 생성 : Sequential API 방식으로 Layer를 쌓는다)
model = keras.models.Sequential()

#3번 모델 블록 조립(모델 레이어 쌓기)
model.add(keras.layers.Input(shape = (13, )))
model.add(keras.layers.Dense(1, activation = "linear"))

#4번 컴파일
model.compile(loss = "mse", optimizer = "adam")

In [ ]:
#학습
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 233162.0469
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 219232.2500
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 205798.7969
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 193003.4844
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 180808.1094
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 169202.7188
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 158083.7031
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 147657.7500
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 137730.9844
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 128300.9922


In [ ]:
#예측값 생성
y_pred = model.predict(x)

16/16 [==============================] - 0s 1ms/step


In [ ]:
y_pred[:10].reshape(-1)

array([327.60953, 311.2962 , 305.4453 , 290.98975, 293.7645 , 293.8535 ,
       337.18286, 344.07108, 338.17426, 336.8009 ], dtype=float32)

In [ ]:
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [ ]:
boston = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv')
boston.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

   lstat  medv  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
3   2.94  33.4  
4   5.33  36.2

In [ ]:
x = boston.iloc[:, : -1]
y = boston.iloc[ : , -1]

In [ ]:
x.shape, y.shape

((506, 12), (506,))

In [ ]:
#모델링 2 : Sequential API

#세션 클리어
keras.backend.clear_session()

#시퀀셜하게 쌓을 거야!
model = keras.models.Sequential()

#레이어 조립
model.add(keras.layers.Input(shape = (12, )))
model.add(keras.layers.Dense(1, activation = "linear"))

#컴파일
model.compile(loss = keras.losses.mean_squared_error, optimizer = keras.optimizers.Adam())

In [ ]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 46557.7031
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 42649.7500
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 39008.3398
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 35617.1250
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 32458.8340
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 29493.8887
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 26756.5859
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 24283.2090
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 21917.5352
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 19790.4336


In [ ]:
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

16/16 [==============================] - 0s 2ms/step


array([-67.971985, -29.922262, -47.9365  , -52.917503, -44.32786 ],
      dtype=float32)

In [ ]:
print(y[:5])

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64


## Logistic Regression 쬐금 더 어려운 데이터

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
from sklearn.datasets import load_breast_cancer #sklearn은 data(x)와 target(y)을 나눠서 저장했다

In [ ]:
cancer = load_breast_cancer()

In [ ]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [ ]:
#모델링 : Sequential API

#1. 세션 클리어 : 기존의 모델이 남아있다면 날려줘!
keras.backend.clear_session()

#2. 레이어 발판 생성 : model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

#3. 레이어 블록 조립 : model에 인풋 값을 받는 레이어를 넣음
model.add(keras.layers.Input(shape=(30, )))

# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add(keras.layers.Dense(1, activation='sigmoid'))

#4. 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'], #분류라서 정확도로 컴파일 해야한다.
              optimizer='adam') #기본적으로 경사하강법

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs = 10, verbose = 1) #loss는 낮을수록 좋다

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 166.8337 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 152.4580 - accuracy: 0.3726
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 138.1690 - accuracy: 0.3726
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 123.7905 - accuracy: 0.3726
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 109.7396 - accuracy: 0.3726
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 95.2726 - accuracy: 0.3726
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 80.8936 - accuracy: 0.3726
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 66.6119 - accuracy: 0.3726
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 52.3018 - accuracy: 0.3726
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 37.9965 - accuracy: 0.3726


In [ ]:
y_pred = model.predict(x)

18/18 [==============================] - 0s 1ms/step


In [ ]:
y_pred[:5]

array([[0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.9748185e-23],
       [0.0000000e+00]], dtype=float32)

In [ ]:
y[:5]

array([0, 0, 0, 0, 0])