# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
#라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import pandas as np
import numpy as np

In [ ]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
x.shape, y.shape #((20,) : 1차원 배열, (20, ) : 1차원 배열), 노드(원)와 layer가 있다

((20,), (20,))

In [ ]:
# 1번 세션 클리어 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언(모델 발판 생성 : Sequential API방식으로 layer를 쌓는다)
model = keras.models.Sequential()

# 3번 모델 블록 조립(모델 레이어 쌓기)
model.add(keras.layers.Input(shape=(1,))) #x에 대한 layer
model.add(keras.layers.Dense(1)) #y에 대한 layer

# 4번 컴파일 
model.compile(loss = 'mse', #예측값과 실제값을 무엇으로 비교할까? 선형학습(지도학습) - 정답에 대한 길을 알려준다
              optimizer='adam') #무조건 adam을 이용, 얼마나 예쁜 방식으로 나갈지? 경사하향법을 이용해서 loss를 줄인다

In [ ]:
model.fit( x, y, epochs=10, verbose=1) #몇번 학습시킬래? epochs, verbose -> 학습되는 과정을 보여준다 0, default 1, 2

Epoch 1/10
1/1 [==============================] - 1s 642ms/step - loss: 850.3654
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 849.6682
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 848.9712
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 848.2746
Epoch 5/10
1/1 [==============================] - 0s 24ms/step - loss: 847.5783
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 846.8823
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 846.1866
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 845.4913
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 844.7963
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 844.1016


In [ ]:
y_pred = model.predict(x) #만들어낸 모델에서 예측값을 뽑아야한다

1/1 [==============================] - 0s 86ms/step


In [ ]:
y_pred.reshape(-1)

array([ 9.9985506e-03, -6.8054354e-01, -1.3710856e+00, -2.0616276e+00,
       -2.7521698e+00, -3.4427121e+00, -4.1332541e+00, -4.8237963e+00,
       -5.5143385e+00, -6.2048807e+00, -6.8954229e+00, -7.5859647e+00,
       -8.2765064e+00, -8.9670486e+00, -9.6575909e+00, -1.0348133e+01,
       -1.1038675e+01, -1.1729218e+01, -1.2419760e+01, -1.3110302e+01],
      dtype=float32)

In [ ]:
y

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
       33, 35, 37])

In [ ]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 30ms/step


array([ 9.9985506e-03, -6.8054354e-01, -1.3710856e+00, -2.0616276e+00,
       -2.7521698e+00, -3.4427121e+00, -4.1332541e+00, -4.8237963e+00,
       -5.5143385e+00, -6.2048807e+00, -6.8954229e+00, -7.5859647e+00,
       -8.2765064e+00, -8.9670486e+00, -9.6575909e+00, -1.0348133e+01,
       -1.1038675e+01, -1.1729218e+01, -1.2419760e+01, -1.3110302e+01],
      dtype=float32)

## Now, Your turn!

In [ ]:
#라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [ ]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [ ]:
x.shape, y.shape #input과 output의 구조, 노드가 1개씩 있고 연결되어있다

((20,), (20,))

In [ ]:
#모델링 : Sequential API 순차적으로 쌓는다

#1. 세션 클리어 : 기존의 모델이 메모리에 남아있다면 지워줘!
keras.backend.clear_session()

#2. 모델을 쌓을 발판 생성
model = keras.models.Sequential()

#3. 모델 블록(layer) 조립
model.add(keras.layers.Input(shape = (1, )))
model.add(keras.layers.Dense(1))

#4. 컴파일
model.compile(loss = "mse", optimizer = "adam") #내 모델이 어떤 형태의 구조, 내 모델이 만든 예측값과 실제 정답을 무엇으로 비교할지,
#경사하강법으로 에러를 줄여나갈건데 그게 얼마나 예쁜 방식으로 내려가게 만들 것인지 결정하는 것
#에러를 MSE로 측정

In [ ]:
model.fit(x, y, epochs = 10, verbose = 1) #1은 프로그래스bar가 기본, 2는 생략

Epoch 1/10
1/1 [==============================] - 0s 423ms/step - loss: 463.0356
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 462.5413
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 462.0473
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 461.5536
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 461.0602
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 460.5670
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 460.0742
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 459.5817
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 459.0895
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 458.5977


In [ ]:
y_pred = model.predict(x)

1/1 [==============================] - 0s 62ms/step


In [ ]:
y_pred[:5]

array([[-0.00999768],
       [-0.37159607],
       [-0.7331944 ],
       [-1.0947928 ],
       [-1.4563912 ]], dtype=float32)

In [ ]:
y[:5] #epochs 값을 크게 하면 값이 정확해질듯? , 뉴럴 네트워크 이용해서 그렸다

array([10,  7,  4,  1, -2])

## Quick Logistic Regression! - 이진 분류

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [ ]:
x.shape, y.shape

((20,), (20,))

In [ ]:
#모델링 : Sequential API

#1. 세션 클리어 : 기존의 모델이 남아있다면 날려줘!
keras.backend.clear_session()

#2. 레이어 발판 생성 : model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

#3. 레이어 블록 조립 : model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )

# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )

#4. 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'], #분류라서 정확도로 컴파일 해야한다.
              optimizer='adam') #기본적으로 경사하강법

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1) #loss는 낮을수록 좋다

# 결과 출력해줘!
print(y)
print(model.predict(x)) #확률이 높을수록 1, 방문한다?

Epoch 1/10
1/1 [==============================] - 1s 554ms/step - loss: 8.9782 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 8.9705 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 8.9628 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 8.9551 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 8.9475 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 8.9398 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 8.9321 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 8.9244 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 8.9167 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 8.9091 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 

## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = np.array(range(40))
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [ ]:
x.shape, y.shape #x라는 특징 하나로 y값 하나를 바라본다 ㅇ(Input(shape = (1, ))) -> ㅇ(Dense(1, activation = "sigmoid"))

((40,), (40,))

In [ ]:
#1. 이전 모델이 있는지 확인하고 지운다
keras.backend.clear_session()

#2. layer 생성
model = keras.models.Sequential()

#3. 레이어 블록 조립
model.add(keras.layers.Input(shape = (1, )))
model.add(keras.layers.Dense(1, activation = "sigmoid"))

#4. 컴파일
model.compile(loss = "binary_crossentropy", metrics = ["accuracy"], optimizer = "adam")

In [ ]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
2/2 [==============================] - 1s 15ms/step - loss: 3.4093 - accuracy: 0.5000
Epoch 2/10
2/2 [==============================] - 0s 10ms/step - loss: 3.3801 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 10ms/step - loss: 3.3495 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 9ms/step - loss: 3.3220 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 9ms/step - loss: 3.2903 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 9ms/step - loss: 3.2636 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 8ms/step - loss: 3.2334 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 3.2051 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 10ms/step - loss: 3.1777 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 9ms/step - loss: 3.1480 - accuracy: 0.4750


In [ ]:
y_pred = model.predict(x)
print(y_pred[:5])
print(y[:5])

2/2 [==============================] - 0s 6ms/step
[[0.50489914]
 [0.4538216 ]
 [0.40369806]
 [0.3555071 ]
 [0.3100775 ]]
[0 0 0 0 0]
