# Keras로 Linear&Logistic Regression 조금 더 맛보기
---

In [3]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

##Linear Regression on 쬐금 더 어려운 데이터

In [15]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
x = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = raw_df.values[1::2, 2]

In [16]:
x.shape, y.shape

((506, 13), (506,))

In [17]:
#1번 세션 클리어 : 이미 만들어진 모델이 있다면 그 모델을 없앤다
keras.backend.clear_session()

#2번 모델 선언(모델 발판 생성 : Sequential API 방식으로 Layer를 쌓는다)
model = keras.models.Sequential()

#3번 모델 블록 조립(모델 레이어 쌓기)
model.add(keras.layers.Input(shape = (13, )))
model.add(keras.layers.Dense(1, activation = "linear"))

#4번 컴파일
model.compile(loss = "mse", optimizer = "adam")

In [19]:
#학습
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 6891.7720
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 5595.1465
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 4509.1836
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 3624.0020
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 2905.0161
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 2323.4299
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 1869.7217
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 1506.2100
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 1226.6913
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 1007.0055


In [20]:
#예측값 생성
y_pred = model.predict(x)

16/16 [==============================] - 0s 1ms/step


In [23]:
print(y_pred[:10].reshape(-1))
print(y[:10])

[33.796444 16.787672 24.224703 27.77741  23.924566 22.531668 31.959406
 18.616072 14.427076 22.594275]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9]


In [24]:
boston = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv')
boston.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

   lstat  medv  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
3   2.94  33.4  
4   5.33  36.2

In [25]:
x = boston.iloc[:, : -1]
y = boston.iloc[ : , -1]

In [26]:
x.shape, y.shape

((506, 12), (506,))

In [28]:
#모델링 2 : Sequential API

#세션 클리어
keras.backend.clear_session()

#시퀀셜하게 쌓을 거야!
model = keras.models.Sequential()

#레이어 조립
model.add(keras.layers.Input(shape = (12, )))
model.add(keras.layers.Dense(1, activation = "linear"))

#컴파일
model.compile(loss = keras.losses.mean_squared_error, optimizer = keras.optimizers.Adam())

In [29]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
16/16 [==============================] - 1s 3ms/step - loss: 5379.4419
Epoch 2/10
16/16 [==============================] - 0s 3ms/step - loss: 4147.5474
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 3118.3301
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 2315.6042
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 1689.9989
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 1225.3678
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 890.3824
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 647.8434
Epoch 9/10
16/16 [==============================] - 0s 3ms/step - loss: 484.9055
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 378.6672


In [30]:
y_pred = model.predict(x)
print(y_pred[:5].reshape(-1))
print(y[:5])

16/16 [==============================] - 0s 1ms/step
[34.185104 33.36761  22.863754 15.605556 20.505924]
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64


## Logistic Regression 쬐금 더 어려운 데이터

In [31]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
from sklearn.datasets import load_breast_cancer #sklearn은 data(x)와 target(y)을 나눠서 저장했다

In [32]:
cancer = load_breast_cancer()

In [33]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [34]:
#모델링 : Sequential API

#1. 세션 클리어 : 기존의 모델이 남아있다면 날려줘!
keras.backend.clear_session()

#2. 레이어 발판 생성 : model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

#3. 레이어 블록 조립 : model에 인풋 값을 받는 레이어를 넣음
model.add(keras.layers.Input(shape=(30, )))

# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add(keras.layers.Dense(1, activation='sigmoid'))

#4. 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'], #분류라서 정확도로 컴파일 해야한다.
              optimizer='adam') #기본적으로 경사하강법

In [35]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs = 10, verbose = 1) #loss는 낮을수록 좋다

Epoch 1/10
18/18 [==============================] - 1s 5ms/step - loss: 26.2007 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 3ms/step - loss: 12.2558 - accuracy: 0.4253
Epoch 3/10
18/18 [==============================] - 0s 5ms/step - loss: 3.0725 - accuracy: 0.7170
Epoch 4/10
18/18 [==============================] - 0s 4ms/step - loss: 1.6844 - accuracy: 0.8682
Epoch 5/10
18/18 [==============================] - 0s 4ms/step - loss: 1.6219 - accuracy: 0.8910
Epoch 6/10
18/18 [==============================] - 0s 4ms/step - loss: 1.5826 - accuracy: 0.8770
Epoch 7/10
18/18 [==============================] - 0s 4ms/step - loss: 1.5687 - accuracy: 0.8752
Epoch 8/10
18/18 [==============================] - 0s 4ms/step - loss: 1.5592 - accuracy: 0.8717
Epoch 9/10
18/18 [==============================] - 0s 4ms/step - loss: 1.5550 - accuracy: 0.8735
Epoch 10/10
18/18 [==============================] - 0s 5ms/step - loss: 1.5464 - accuracy: 0.8717


In [36]:
y_pred = model.predict(x)
print(y_pred[:5])
print(y[:5])

18/18 [==============================] - 0s 1ms/step
[[0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [3.8282682e-08]
 [8.4345375e-09]]
[0 0 0 0 0]
