# 멀티클래스 분류 연습 (over 2진분류)
---
![iris_flower](https://www.embedded-robotics.com/wp-content/uploads/2022/01/Iris-Dataset-Classification-1024x367.png)

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
x = iris.data
y = iris.target

In [ ]:
x.shape, y.shape #위 클래스는 3개인데 y는 1개이다.. 어떻게 접근해야 할까

((150, 4), (150,))

In [ ]:
y #0 - setosa, 1 - versicolor, 2 - virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
#sepal - length, width와 petal - length, width column이 하나의 y를 바라보고 있다?

In [ ]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y, 3) #한 번만 실행해야한다. 안 그럼 차원이 늘어난다

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

## 1번. Sequential API style로 모델링 하세요

- loss = 'categorical_crossentropy' 사용!

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

#1. 이전 모델이 있는지 확인하고 지운다
keras.backend.clear_session()

#2. layer 생성
model = keras.models.Sequential()

#3. 레이어 블록 조립
model.add(keras.layers.Input(shape = (4, )))
model.add(keras.layers.Dense(3, activation = "softmax"))

#4. 컴파일
model.compile(loss = "categorical_crossentropy", metrics = ["accuracy"], optimizer = "adam")

#5. 요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#선 하나하나가 전부 가중치
#Param 의미 : (4 + 1(편향값)) * 3 = 학습 가능한 parameter가 총 15개가 된다
#그 다음 레이어의 노드 수 = 첫 번째 레이어 : 4(노드) * 3(target) , 두 번째 레이어 : 3(target)
#연결주의 관점에서는 편향값을 일부러 준다
#또 다른 값을 줌으로써 모델의 학습을 일부러 흔든다. 그래서 다른 값도 더해서
#모델을 일반적으로 사용 가능하게 만드는 과정이라고 보면 된다

In [ ]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 1s 4ms/step - loss: 1.6224 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 1.5586 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 1.4982 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 1.4404 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 1.3843 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3395 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2939 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2533 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2186 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 1.1866 - accuracy: 0.3333


In [ ]:
#Epoch 5/5 : mini-batch = 1 epoch에서 update 된 횟수
#10000개의 데이터 = Batch? 

In [ ]:
y_pred = model.predict(x)
print(y_pred[:5]) #편향값이라고 기본적으로 내재된 값이라 생각
#setosa, versicolor, virginica
print(y[:5])

5/5 [==============================] - 0s 2ms/step
[[0.14607143 0.27889147 0.5750371 ]
 [0.18226817 0.31424367 0.5034882 ]
 [0.15923929 0.29081172 0.5499489 ]
 [0.13714497 0.28152525 0.58132976]
 [0.1300162  0.26332068 0.6066631 ]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## 2번. Functional API style로 모델링 하세요

In [ ]:
x.shape, y.shape